baseURL = 'https://harthoover.com/'
languageCode = 'en-us'
title = 'Hart Hoover'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Hart Hoover"
  headline = "Technology, coffee, and tacos"
  image = "https://avatars.githubusercontent.com/u/579484"
  links = [
    { linkedin = "https://linkedin.com/in/harthoover" },
    { github = "https://github.com/hhoover" },
    { bluesky = "https://bluesky.com/harthoover.com" },
    { youtube = "https://www.youtube.com/@AceOfHarts" },
    { instagram = "https://instagram.com/harthoover" },
    { signal = { icon = "signal", href="https://signal.me/#eu/ignUk4e7qzgFRg2lxNg-b1IUOlA_oTX9DVKIlD2aGFrnFePJeHdF-bsGNVJERfEi", text = "Signal" } },
    { tiktok = "https://www.tiktok.com/@harthoover?_t=ZT-8ujt2r6OMzD&_r=1" },
    { gamepad = { href = "https://www.extra-life.org/index.cfm?fuseaction=donorDrive.participant&participantID=551126", text = "Donate to ExtraLife" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.imports]]
    path = "github.com/jpanther/lynx"